<div style = "padding:100px; padding-top:10px">
    <?php echo $this->report; ?>

</div>

<?php
require_once ('html2pdf/html2pdf.class.php');
$content = '<page style="font-family: freeserif"><br />'.ob_get_clean().'</page>';
$pdf = new HTML2PDF("P", "A4", "it", true, "UTF-8", array(10,10,10,10));
$pdf->writeHTML($content);
$pdf->output($this->nomepdf. ".pdf", "D");
?>

//<?
//require_once ('html2pdf_v4.03/html2pdf.class.php');
//
//    // get the HTML
//
//
//    $content = '<page style="font-family: freeserif"><br />'.ob_get_clean().'</page>';
//
//
//
//try{
//$pdf = new HTML2PDF("P", "A4", "it", true, 'UTF-8');
//$pdf->pdf->SetDisplayMode('real');
//
//$pdf->writeHTML($content, isset($_GET['vuehtml']));
//$pdf->output($this->nomepdf. ".pdf", "D");
//}
//catch(HTML2PDF_exception $e) {
//        echo $e;
//        exit;
//    }
//?>

